<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation\State;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var State $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<?php $filters = $block->getActiveFilters() ?>
<?php if (!empty($filters)): ?>
<div
    x-data="{ open: true }"
    class="filter-current bg-container-lighter border border-gray-10 border-container p-3"
>
    <h3 id="active-filtering-heading">
        <strong class="font-primary font-bold font-xs leading-6 text-xs text-primary uppercase mb-2"><?= $escaper->escapeHtml(__('Now shopping by')) ?></strong>
    </h3>
    <div
        id="active-filtering-content"
        x-show="open"
        x-transition:enter="transition ease-out duration-300"
        x-transition:leave="transition ease-in duration-200"
        aria-labelledby="active-filtering-heading"
        role="region"
    >
        <?php foreach ($filters as $filter): ?>
            <?php
                $filterName = $filter->getName();
                $filterLabel = $block->stripTags($filter->getLabel());
            ?>
            <div class="item flex justify-between items-center">
                <div class="flex flex-row justify-between items-center">
                    <a class="text-center block action remove mr-2"
                       href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                       title="<?= /* @noEscape */ $escaper->escapeHtmlAttr(__('Remove active %1 filter: %2', $filterName, $filterLabel)) ?>">
                        <?= $hyvaicons->renderHtml('closeMenu', 'w-4 h-4');?>
                    </a>
                    <span class="filter-label block font-primary font-bold font-xs leading-6 text-primary mr-2"><?= $escaper->escapeHtml(__($filterName)) ?>:</span>
                    <span class="filter-value text-sm block font-primary font-normal font-xs leading-6 text-primary"><?= $escaper->escapeHtml($filterLabel) ?></span>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if ($block->getLayer()->getState()->getFilters()): ?>
        <div class="block-actions filter-actions mt-2">
            <a href="<?= $escaper->escapeUrl($block->getClearUrl()) ?>"
               class="font-primary font-normal font-xs leading-5 text-secondary hover:underline"><?= $escaper->escapeHtml(__('Clear all filters')) ?></a>
        </div>
    <?php endif; ?>
</div>
<?php endif; ?>
