<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;
use Hyva\Theme\ViewModel\SvgIcons;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);


?>


<?php if ($block->canShowBlock()): ?>
    <div
        x-data="initLayeredNavigation()"
        x-init="checkIsMobileResolution()"
        @resize.window.debounce="checkIsMobileResolution()"
        @visibilitychange.window.debounce="checkIsMobileResolution()"
        role="region"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
    >
        <h2
            id="filters-heading"
            class="block-title"
        >

            <button
                type="button"
                @click="blockOpen = !blockOpen"
                aria-controls="filters-content"
                :aria-expanded="blockOpen"
                :aria-disabled="!isMobile"
                :disabled="!isMobile ? '' : null"

                class="btn__secondary h-[2.625] items-center justify-center text-sm tracking-wider shadow-md px-3 py-2 md:hidden lg:hidden" aria-label="Secondary mobile">
                <?= $escaper->escapeHtml(__('Shop By')) ?>

                <span class="ml-2">
                    <?= $hyvaicons->renderHtml('filterIcon', '', 14, 14); ?>
                </span>
            </button>

        </h2>


        <div
            id="filters-content"
            x-show="blockOpen" x-transition
            class="block-content tablet:max-w-[329px] filter-content hidden md:block lg:block absolute md:relative lg:relative top-0 left-0 tablet:ml-0 tablet:pl-0 right-0 w-full h-screen z-40 tablet:z-0 bg-white p-3 pt-0 tablet:pr-0"
            :class="{ 'hidden': !blockOpen }"
            :class="{ 'scrollbar-none': blockOpen }">

            <div class="flex flex-row justify-end">
                <button
                    @click="blockOpen = !blockOpen"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                    type="button">
                    <div class="flex row items-center mt-6 md:hidden lg:hidden">
                        <p class="font-normal text-text-color leading-5 text-md font-primary">Close</p>
                        <span class="ml-2"> <?= $hyvaicons->renderHtml('closeMenu', 'w-3 h-3');?></span>
                    </div>
                </button>
            </div>

            <h2 class="font-primary font-bold uppercase font-sm leading-6 text-primary mb-6">
                Shopping options
            </h2>

            <?= $block->getChildHtml('state') ?>
            <a
                href="#product-list"
                class="sr-only focus:not-sr-only bg-blue-600 text-white px-12 py-4 text-center block"
            >
                <?= $escaper->escapeHtml(__('Skip to product list')) ?>
            </a>

            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <div
                        x-data="{
                            open: false,
                            id: $id('filter-option')
                        }"
                        class="filter-option border-b md:border-0 lg:border-0 mt-2"
                    >
                        <h3 :id="`${id}-title`" class="border-b py-2">
                            <button
                                type="button"
                                @click="open = !open"
                                class="filter-options-title flex justify-between items-center cursor-pointer text-start hover:text-secondary-darker w-full"
                                :aria-controls="`${id}-content`"
                                :aria-expanded="open"
                            >
                                <span class="title font-primary md:font-heading lg:font-heading font-bold text-xs tablet:text-sm leading-6 md:font-normal lg:font-normal md:leading-5 lg:leading-5 tracking-wide text-text-color uppercase">
                                    <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                    <span class="sr-only"> <?= $escaper->escapeHtml(__('filter')) ?></span>
                                </span>
                                    <span class="py-[0.625rem]">
                                    <?= $heroicons->chevronDownHtml('',
                                        14,
                                        14,
                                        [
                                            ":class" => "{ 'rotate-180': open }",
                                            "aria-hidden" => "true",
                                            "focusable" => "false"
                                        ]
                                    ); ?>
                                </span>
                            </button>
                        </h3>
                        <template x-if="open" x-show="open">
                            <div
                                :id="`${id}-content`"
                                x-transition
                                class="filter-options-content ml-3 font-primary uppercase font-normal text-xs tablet:text-sm leading-6 tracking-wide text-text-color">
                                <?= /* @noEscape */ $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                            </div>
                        </template>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>


    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 768px)').matches;

                    this.blockOpen = window.matchMedia('(min-width: 768px)').matches;

                }

            };
        }
    </script>

<?php endif; ?>
