<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\Theme\ViewModel\StoreConfig;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

$storeConfig = $viewModels->require(StoreConfig::class);

?>

<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="bg-secondary relative">

    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenu($root)"
         class="mx-auto hidden w-full lg:block lg:min-h-0">

        <nav class="mx-24" aria-label="<?= $escaper->escapeHtmlAttr(__('navigation menu')) ?>">
            <ul class="container mx-auto flex items-center">
                <?php foreach ($menuItems as $index => $menuItem): ?>
                    <li class="level-0 before:content-[''] mb-0 block hover:text-white visited:text-white"
                        @mouseenter="hoverPanelActiveId = '<?= /* @noEscape */ (string) $index ?>'"
                        @mouseleave="hoverPanelActiveId = 0"
                        @keyup.escape="hoverPanelActiveId = 0"
                        style="text-shadow: 0 0.125rem 0.313rem black;">
                <span class="mr-6 flex items-center py-4">
                    <a class="mr-2 w-full text-xs font-normal uppercase leading-5 tracking-widest text-white font-heading hover:underline"
                       href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                       title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                       @focus="hoverPanelActiveId = 0">
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </a>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <button
                            type="button"
                            data-sr-button-id="<?= $escaper->escapeHtmlAttr($index) ?>"
                            :aria-expanded="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'true' : 'false'"
                            @click="openMenuOnClick('<?= /* @noEscape */ (string) $index ?>')"
                            >
                            <span aria-hidden="true">
                                <svg width="10" height="6" viewBox="0 0 9 6" fill="#4e4e4e" class="fill-white transition-transform duration-200" :class="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'rotate-180' : ''" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M0.242039 1.66243L3.91704 5.16243C4.15652 5.39051 4.54424 5.39051 4.78311 5.16243L8.45811 1.66243C8.6976 1.43435 8.6976 1.0651 8.45811 0.837597C8.21862 0.610097 7.83091 0.609514 7.59204 0.837597L4.35007 3.92518L1.10811 0.837597C0.868626 0.609514 0.480913 0.609514 0.242039 0.837597C0.00316362 1.06568 0.00255111 1.43493 0.242039 1.66243Z"/>
                                </svg>
                            </span>
                            <span class="sr-only">
                                <?= $escaper->escapeHtml(__('Show submenu for %1 category', $menuItem['name'])) ?>
                            </span>
                        </button>
                    <?php endif; ?>
                </span>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <ul class="absolute left-0 bg-white shadow-md block flex w-full py-6 justify-center z-30"
                                :class="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'scale-y-100' : 'scale-y-0'">
                                <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                    <li style="text-shadow: none;" class="before:content-[''] mr-8 flex flex-col items-start">
                                        <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                           title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                           class="block w-full font-bold text-xs leading-5 tracking-wide uppercase hover:underline"
                                           @keyup.escape="$nextTick(() => document.querySelector('[data-sr-button-id=<?= $escaper->escapeJs($index) ?>]').focus())">
                                    <span class="text-xs leading-5 tracking-wide uppercase text-black">
                                        <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                    </span>
                                        </a>
                                        <?php if (!empty($subMenuItem['childData'])): ?>
                                            <ul class="mt-6">
                                                <?php foreach ($subMenuItem['childData'] as $products): ?>
                                                    <li class="before:content-[''] block max-w-[13.125rem]">
                                                        <a
                                                            href="<?= $escaper->escapeUrl($products['url']) ?>"
                                                            title="<?= $escaper->escapeHtmlAttr($products['name']) ?>"
                                                            class="text-black text-xs leading-5 tracking-wide uppercase text-black hover:underline"
                                                        >
                                                            <?= $escaper->escapeHtml($products['name']) ?>
                                                        </a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    </li>
                                <?php endforeach; ?>
                                <li class="before:content-[''] flex flex-col items-start font-normal text-xs text-black font-primary leading-6 tracking-wide" style="text-shadow: none;">
                                    <a href="/contact/" class="block w-full text-xs font-bold font-primary hover:underline leading-6 tracking-wide uppercase">
                                        <?= $escaper->escapeHtmlAttr(__('Contact us')) ?>
                                    </a>

                                    <ul class="mt-4 ml-0 normal-case">
                                        <li class="before:content-[''] flex flex-row items-center hover:underline cursor-pointer">
                                            <?= $hyvaicons->renderHtml('location', 14,14); ?>
                                            <a href="https://www.google.com/maps/place/Trg+slobode+6,+31000,+Osijek/@45.5600728,18.6757394,17z/data=!3m1!4b1!4m6!3m5!1s0x475ce7a7b55a4fdf:0x7b0024dd0595b47b!8m2!3d45.5600691!4d18.6783143!16s%2Fg%2F11n0__57zw?entry=ttu" target="_blank">
                                                <span class="ml-2">
                                                    <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/street_line1') ?? ''); ?>
                                                </span>
                                            </a>
                                        </li>
                                        <li class="before:content-[''] flex flex-row items-center hover:underline cursor-pointer">
                                            <?= $hyvaicons->renderHtml('tel', 14, 14); ?>
                                            <a href="tel:+385958811630" target="_blank">
                                                <span class="ml-2">
                                                    <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/phone') ?? ''); ?>
                                                </span>
                                            </a>
                                        </li>
                                        <li class="before:content-[''] flex flex-row items-center hover:underline cursor-pointer">
                                            <?= $hyvaicons->renderHtml('email', 14, 14); ?>
                                            <a href="mailto:filip.svetlicic@gmail.com" target="_blank">
                                                <span class="ml-2">
                                                    <?= $escaper->escapeHtml($storeConfig->getStoreConfig('trans_email/ident_general/email') ?? ''); ?>
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                <li class="block before:content-[''] mr-6 flex flex-row items-center py-4 mb-0" style="text-shadow: 0 0.125rem 0.313rem black;">
                    <a href="<?= $escaper->escapeUrl($block->getUrl('contact')) ?>" class="hover:underline text-xs font-normal uppercase leading-5 tracking-wide font-heading text-white">
                        <?= $escaper->escapeHtmlAttr(__('Contact us')) ?>
                    </a>
                </li>
            </ul>
        </nav>

    </div>
</div>

<script>
    'use strict';

    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            hoverPanelActiveId: null,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0')
                });
            },
            openMenuOnClick(menuNode) {
                if (menuNode === this.hoverPanelActiveId) {
                    this.hoverPanelActiveId = 0;
                } else {
                    this.hoverPanelActiveId = menuNode
                }
            }
        }
    }
</script>
