<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="bg-secondary relative"
>
    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenu($root)"
         class="hidden lg:block lg:min-h-0 lg:px-24 lg:w-auto lg:pt-0">
        <nav
            class="duration-150 ease-in-out transform w-auto relative min-h-0 transition-display"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>"
        >
            <ul class="flex justify-start">
                <?php foreach ($menuItems as $index => $menuItem): ?>
                    <li class="level-0"
                        @mouseenter="hoverPanelActiveId = '<?= /* @noEscape */ (string) $index ?>'"
                        @mouseleave="hoverPanelActiveId = 0"
                        @keyup.escape="hoverPanelActiveId = 0"
                    >
                        <span class="flex items-center gap-1 mr-6 font-heading text-white uppercase font-normal text-xs py-4 leading-5 tracking-wide">
                            <a class="w-full font-heading text-white uppercase font-normal text-xs leading-5 tracking-wider"
                               href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                               title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                               @focus="hoverPanelActiveId = 0"
                            >
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </a>
                            <?php if (!empty($menuItem['childData'])): ?>
                                <button
                                    type="button"
                                    data-sr-button-id="<?= $escaper->escapeHtmlAttr($index) ?>"
                                    :aria-expanded="hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>' ? 'true' : 'false'"
                                    @click="openMenuOnClick('<?= /* @noEscape */ (string) $index ?>')"
                                >
                                    <?= $heroiconsSolid->chevronDownHtml("flex self-center h-5 w-5", 25, 25, ['aria-hidden' => 'true']) ?>
                                    <span class="sr-only">
                                        <?= $escaper->escapeHtml(__('Show submenu for %1 category', $menuItem['name'])) ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                        </span>

                        <?php if (!empty($menuItem['childData'])): ?>
                            <div>
                                <ul
                                    class="absolute left-0 z-10 bg-white hidden shadow-lg w-full h-auto py-6"
                                    :class="{
                                    'hidden' : hoverPanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                                    'block' : hoverPanelActiveId === '<?= /* @noEscape */ (string) $index ?>'
                                }"
                                >
                                    <?php foreach ($menuItems as $index2 => $menuItem): ?>

                                            <li class="flex flex-row text-center justify-center">
                                                <a href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                                   title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                                                   class="block w-full px-3 py-1 my-1 whitespace-nowrap first:mt-0 hover:underline"
                                                   @keyup.escape="$nextTick(() => document.querySelector('[data-sr-button-id=<?= $escaper->escapeJs($index2) ?>]').focus())"
                                                >
                                            <span class="font-primary font-bold text-sm leading-6 tracking-wide uppercase">
                                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                                            </span>
                                                </a>
                                            </li>

                                    <?php endforeach; ?>

                                    <?php foreach ($menuItem['childData'] as $subMenuItem): ?>

                                        <li class="flex flex-row text-center justify-center">
                                            <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                               title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                               class="block w-full px-3 py-1 my-1 whitespace-nowrap first:mt-0 hover:underline"
                                               @keyup.escape="$nextTick(() => document.querySelector('[data-sr-button-id=<?= $escaper->escapeJs($index) ?>]').focus())"
                                            >
                                            <span class="font-primary font-bold text-sm leading-6 tracking-wide uppercase">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                                            </a>
                                        </li>

                                    <?php endforeach; ?>

                                </ul>
                            </div>
                        <?php endif; ?>

                    </li>
                <?php endforeach; ?>
                <ul class="flex flex-row items-center">
                    <li class="font-heading text-white uppercase font-normal text-xs py-4 leading-5 tracking-wide"><a href="#">Contact us</a></li>
                </ul>
            </ul>
        </nav>
    </div>


</div>
<script>
    'use strict';

    const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            hoverPanelActiveId: null,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item
                    item.closest('div.level-0') &&
                    item.closest('div.level-0').querySelector('a.level-0')
                });
            },
            openMenuOnClick(menuNode) {
                if (menuNode === this.hoverPanelActiveId) {
                    this.hoverPanelActiveId = 0;
                } else {
                    this.hoverPanelActiveId = menuNode
                }
            }
        }
    }
</script>
