<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<nav
    x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
    @load.window="setActiveMenu($root)"
    @keydown.window.escape="closeMenu()"
    class="z-20 order-2 sm:order-1 lg:order-2 items-center navigation lg:hidden flex flex-row items-center justify-center ml-5"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation"
>
    <!-- mobile -->
    <button
        x-ref="mobileMenuTrigger"
        @click="openMenu()"
        :class="{'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open">

        <?= $hyvaicons->renderHtml('hamburgerIcon', '', 18, 18, [":class" => "{ 'hidden' : open, 'block': !open }", "aria-hidden" => "true"]); ?>
    </button>

    <div
        x-show="open"
        x-transition:enter="transition ease-out duration-300 transform"
        x-transition:enter-start="opacity-0 scale-95"
        x-transition:enter-end="opacity-100 scale-100"
        x-ref="mobileMenuNavLinks"
        class="
        fixed top-0 right-0 w-full h-screen p-1
        flex-col border-0 border-container bg-container-lighter
        overflow-y-auto overflow-x-hidden bg-white"

        :class="{ 'flex': open, 'hidden': !open }"
        :aria-hidden="open ? 'false' : 'true'"
        role="dialog"
        aria-modal="true">

        <p class="font-normal mx-3 mb-6 text-md leading-6 mt-16 text-primary uppercase font-primary"><?= $escaper->escapeHtmlAttr(__('Menu')) ?></p>

        <nav class="mx-3">
            <ul aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>">
                <?php foreach ($menuItems as $index => $menuItem): ?>
                    <li data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main" class="level-0 border-b border-text-gray">

                        <div x-data="{ rot: 0 }" class="hover:underline flex flex-row justify-between items-center font-primary text-xs font-bold my-2 uppercase text-text-color leading-6 tracking-wide">
                            <a href="<?= $escaper->escapeUrl($menuItem['url']) ?>" title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>">
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </a>

                            <?php if (!empty($menuItem['childData'])): ?>
                                <button @click="openSubcategory('<?= /* @noEscape */ $index ?>'); rot = rot === 0 ? 180 : 0" x-bind:style="'transform: rotate(' + rot + 'deg)'" aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $menuItem['name'])) ?>" aria-haspopup="true" :aria-expanded="mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'">
                                    <span>
                                        <?= $hyvaicons->renderHtml('dropdownIcon', '', 14, 14); ?>
                                    </span>
                                </button>
                            <?php endif; ?>
                        </div>

                        <?php if (!empty($menuItem['childData'])): ?>
                            <div data-child-id="<?= $escaper->escapeHtmlAttr($index) ?>" :class="{ 'hidden': mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>'}">
                                <ul aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>">
                                    <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                        <li class="flex flex-col justify-start font-primary text-xs uppercase my-2 font-normal leading-6 tracking-wide text-text-color" x-data="{ isOpen: false, rotate: 0 }" >
                                            <div class="flex justify-start items-center" x-data="{ rotate: 0 }">

                                                <?php if (!empty($subMenuItem['childData'])): ?>
                                                    <button @click="isOpen = !isOpen; rotate += 45" x-bind:style="'transform: rotate(' + rotate + 'deg)'" class="toggle-icon ml-3 mr-2">
                                                        <span>
                                                            <?= $hyvaicons->renderHtml('subCategoryIcon', 'cursor-pointer', 14, 14);?>
                                                        </span>
                                                    </button>
                                                <?php endif; ?>

                                                <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>" title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>" class="submenu-link hover:underline">
                                                    <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                                </a>
                                            </div>
                                            <?php if (!empty($subMenuItem['childData'])): ?>
                                                <div>
                                                    <ul x-show="isOpen" class="ml-12" x-transition:enter="transition ease-out duration-300 transform" x-transition:enter-start="opacity-0 scale-95" x-transition:enter-end="opacity-100 scale-100">
                                                        <?php foreach ($subMenuItem['childData'] as $products): ?>
                                                            <li class="hover:underline my-2">
                                                                <a href="<?= $escaper->escapeUrl($products['url']) ?>" title="<?= $escaper->escapeHtmlAttr($products['name']) ?>" class="sub-submenu-link">
                                                                    <?= $escaper->escapeHtml($products['name']) ?>
                                                                </a>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>
                                                </div>
                                            <?php endif; ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif; ?>

                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>

        <button
            @click="closeMenu()"
            class="absolute flex justify-end w-16 self-end mb-1"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
            type="button">
            <span class="'hidden' : !open, 'block': open">
               <div class="flex row items-center mt-6 mr-3">
                   <p class="font-normal text-text-color leading-5 text-xs font-primary"><?= $escaper->escapeHtmlAttr(__('Close')) ?></p>
                <span class="ml-2"> <?= $hyvaicons->renderHtml('closeMenu', '', 12, 12);?></span>
               </div>
            </span>
        </button>
    </div>
</nav>



<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.closest('li.level-0') &&
                    item.closest('li.level-0').querySelector('a.level-0');
                });
            },
            openMenu() {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']));
                document.body.style.position = 'fixed';
            },
            closeMenu() {
                document.body.style.position = '';

                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }

                this.open = false
                this.mobilePanelActiveId = null
            },
            openSubcategory(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']')
                this.mobilePanelActiveId = this.mobilePanelActiveId === index ? 0 : index
                this.$nextTick(() => hyva.trapFocus(menuNodeRef))
            },
            backToMainCategories(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']')
                this.mobilePanelActiveId = 0
                this.$nextTick(() => {
                    hyva.trapFocus(this.$refs['mobileMenuNavLinks'])
                    menuNodeRef.querySelector('a').focus()
                })
            }
        }
    }
</script>
