<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<nav
    x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
    @load.window="setActiveMenu($root)"
    @keydown.window.escape="closeMenu()"
    class="z-20 order-2 sm:order-1 lg:order-2 navigation lg:hidden w-12 h-12"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation"
>
    <!-- mobile -->
    <button
        x-ref="mobileMenuTrigger"
        @click="openMenu()"
        :class="{'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open"
    >
        <?= $heroicons->menuHtml('p-3', 48, 48, [":class" => "{ 'hidden' : open, 'block': !open }", "aria-hidden" => "true"]) ?>
    </button>

    <div
        x-ref="mobileMenuNavLinks"
        class="
            fixed top-0 right-0 w-full h-screen p-1 hidden
            flex-col border-0 border-container bg-container-lighter
            overflow-y-auto overflow-x-hidden bg-white
        "
        :class="{ 'flex': open, 'hidden': !open }"
        :aria-hidden="open ? 'false' : 'true'"
        role="dialog"
        aria-modal="true">

        <p class="font-normal mx-4 mb-6 text-md leading-6 mt-16 text-primary uppercase font-primary">Menu</p>



        <nav>
            <ul
                class="mx-4 flex flex-col gap-y-1"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>">
                <?php foreach ($menuItems as $index => $menuItem): ?>
                    <li
                        data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main"
                        class="level-0">
                        <div
                            class="flex items-center"
                            :class="{
                            '-translate-x-0' : mobilePanelActiveId,
                            'translate-x-0' : !mobilePanelActiveId}">
                            <a
                                class="flex items-center w-full py-2 border-b cursor-pointer
                                bg-container-lighter border-container level-0 font-bold text-primary uppercase leading-6 tracking-wide text-text-color text-xs hover:underline"
                                href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>">
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </a>
                            <?php if (!empty($menuItem['childData'])): ?>
                                <button
                                    @click="openSubcategory('<?= /* @noEscape */ $index ?>')"
                                    class="absolute right-0 flex items-center mr-3 w-3 h-3 cursor-pointer bg-container-lighter border-container transition-transform transform origin-right"
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $menuItem['name'])) ?>"
                                    aria-haspopup="true"
                                    :aria-expanded="mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'"
                                    :class="{ 'rotate-180': mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>' }">
                                    <div>
                                        <span class="w-full h-full p-1">
                                            <?= $hyvaicons->renderHtml('dropdownIcon', ''); ?>
                                        </span>
                                    </div>
                                </button>
                            <?php endif; ?>
                        </div>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <div
                                data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>"
                                class="z-30 w-full h-full p-1 bg-container-lighter"
                                :class="{
                                'hidden': mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>'}">
                                <ul aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>">
                                    <li>
                                        <a
                                            href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                            title="<?= $escaper->escapeHtmlAttr($menuItem['name'])?>"
                                            class="cursor-pointer hover:underline">
                                        </a>
                                    </li>
                                    <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                        <ul class="flex flex-row items-center">
                                            <li class="flex flex-row-reverse">
                                                    <span class="h-10 font-normal font-primary text-xs uppercase leading-6 tracking-wider">
                                                        <a href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                                           class="hover:underline"
                                                           title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>">
                                                        <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                                        </a>
                                                    </span>

                                                <?php if (!empty($subMenuItem['childData'])): ?>
                                                    <div x-data="{ isOpen: false, rotate: 0 }" class="inline">
                                                        <span @click="isOpen = !isOpen; rotate += 45"
                                                              x-bind:style="'transform: rotate(' + rotate + 'deg)'"
                                                              class="cursor-pointer mr-2 inline-block transition-transform transform origin-center">
                                                            <?= $hyvaicons->renderHtml('subCategoryIcon', 'w-3 h-3');?>
                                                        </span>
                                                        <ul x-show="isOpen" class="ml-12">
                                                            <?php foreach ($subMenuItem['childData'] as $products): ?>
                                                                <li>
                                                                    <a href="<?= $escaper->escapeUrl($products['url']) ?>"
                                                                       title="<?= $escaper->escapeHtmlAttr($products['name']) ?>"
                                                                       class="text-black text-xs leading-5 tracking-wide uppercase text-black hover:underline">
                                                                        <?= $escaper->escapeHtml($products['name']) ?>
                                                                    </a>
                                                                </li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    </div>
                                                <?php endif; ?>
                                            </li>
                                        </ul>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
        <button
            @click="closeMenu()"
            class="absolute flex justify-end w-16 self-end mb-1"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
            type="button">
            <span class="'hidden' : !open, 'block': open">
               <div class="flex row items-center mt-6 mr-3">
                   <p class="font-normal text-text-color leading-5 text-xs font-primary">Close</p>
                <span class="ml-2"> <?= $hyvaicons->renderHtml('closeMenu', 'w-3 h-3');?></span>
               </div>
            </span>
        </button>
    </div>
</nav>





<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.closest('li.level-0') &&
                    item.closest('li.level-0').querySelector('a.level-0');
                });
            },
            openMenu() {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']));
                // Prevent from body scrolling while mobile menu opened
                document.body.style.position = 'fixed';
            },
            closeMenu() {
                document.body.style.position = '';

                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }

                this.open = false
                this.mobilePanelActiveId = null
            },
            openSubcategory(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']')
                this.mobilePanelActiveId = this.mobilePanelActiveId === index ? 0 : index
                this.$nextTick(() => hyva.trapFocus(menuNodeRef))
            },
            backToMainCategories(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']')
                this.mobilePanelActiveId = 0
                this.$nextTick(() => {
                    hyva.trapFocus(this.$refs['mobileMenuNavLinks'])
                    menuNodeRef.querySelector('a').focus()
                })
            }
        }
    }
</script>
