<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="toolbar-sorter sorter flex items-center order-1 col-span-3 sm:col-span-6
        md:col-span-3 lg:col-span-6 justify-end">

    <span class="hidden whitespace-nowrap tablet:block desktop:block mr-3 font-primary font-normal font-md leading-6 text-text-gray">
        <?= $escaper->escapeHtml(__('Sort by:')) ?>
    </span>

    <select data-role="sorter"
            class="mr-2 focus:border-text-color focus:ring-0 focus:ring-0 border-1 border-gray-25 font-primary text-text-color font-normal leading-6 font-sm h-11 h-[42px] min-w-[110px]"
            aria-label="<?= $escaper->escapeHtml(__('Sort By')) ?>"
            @change="changeUrl(
                'product_list_order',
                $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                options.orderDefault
            )">

        <?php foreach ($block->getAvailableOrders() as $orderCode => $orderLabel):?>
            <option value="<?= $escaper->escapeHtmlAttr($orderCode) ?>"
                <?php if ($block->isOrderCurrent($orderCode)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $escaper->escapeHtml(__($orderLabel)) ?>
            </option>
        <?php endforeach; ?>
        </select>


    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           @click.prevent="changeUrl('product_list_dir', 'asc', options.directionDefault)"
        >
            <?= $hyvaicons->renderHtml('filterArrow', '', 14, 14); ?>
        </a>
    <?php else: ?>
        <a title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc transform rotate-180"
           @click.prevent="changeUrl('product_list_dir', 'desc', options.directionDefault)"
        >
            <?= $hyvaicons->renderHtml('filterArrow', '', 14, 14); ?>
        </a>
    <?php endif; ?>

</div>
