<h2 class="uppercase text-2xl mt-4 text-black"><?= __('Atoms') ?></h2>

<p class="text-xl mt-6 mb-4"><?= __('Main colors') ?></p>

<div class="flex direction-row items-center mb-6">
    <div class="w-16 h-16 bg-primary rounded-full"></div>
    <p class="ml-4"><?= __('--primary__color') ?></p>
</div>

<div class="flex direction-row items-center">
    <div class="w-16 h-16 bg-secondary rounded-full"></div>
    <p class="ml-4"><?= __('--secondary__color') ?></p>
</div>
