<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$uniqueId = '_' . uniqid();
// Orderfooter is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>


<div>
    <p class="font-heading font-normal text-center text-xl leading-11 text-black my-5">Featured categories</p>
</div>

<div class="flex flex-col items-center desktop:flex-row desktop:justify-center">
    <div class="grid px-3 grid-cols-1 grid-rows-4 w-full desktop:grid-cols-4 desktop:grid-rows-1 desktop:gap-7 md:grid-cols-2 md:grid-rows-2 md:gap-7">

        <?php foreach ($menuItems as $index => $menuItem): ?>
            <div class="relative mb-6 w-full">
                <a href="<?= $escaper->escapeUrl($menuItem['url']) ?>" title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>" class="relative block">
                    <img src="<?= $escaper->escapeHtml($menuItem['image']) ?>" alt="category_image_<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>" class="w-full cover">
                    <span class="hover:text-secondary transition duration-300 absolute z-20 bottom-4 left-3 mr-2 text-base desktop:text-xl font-normal leading-5 desktop:leading-7 tracking-widest text-white font-heading"
                          style="text-shadow: 0px 2px 5px black;">
                        <?= $escaper->escapeHtml($menuItem['name']) ?>
                    </span>
                    <div class="absolute inset-0 bg-gradient-to-b from-transparent to-[#00000050] hover:to-[#00000075]"></div>
                </a>
            </div>
        <?php endforeach; ?>

    </div>
</div>


