<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$cssClass = $block->getCssClass() ? 'text-2xl' . $block->getCssClass() : 'text-3xl';
$titleHtml = '';
if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span style="text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $escaper->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>

<?php if ($titleHtml): ?>
    <div class="flex flex-col md:flex-row flex-wrap font-bold py-3 <?= /** @noEscape */ $cssClass ?>">
        <h1 class="text-gray-900 page-title title-font"
            <?php if ($block->getId()): ?> id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>>
            <?= /* @noEscape */ $titleHtml ?>

        </h1>
        <?= $block->getChildHtml() ?>

    </div>
<?php endif; ?>
