<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\View\Element\Template;

/** @var ViewModelRegistry $viewModels */
/** @var Slider $sliderViewModel */
/** @var Template $block */

$sliderViewModel = $viewModels->require(Slider::class);

/**
 * These items are examples. You could query products, categories, etc..
 * Change the slider-item.phtml accordingly to display the correct properties.
 */
$items = [
    [
        'image_url'    => $block->getViewFileUrl('images/slider-1.webp'),
        'image_width'  => 1600,
        'image_height' => 624,
        'text_small'   => '',
        'text_large'   => 'THE FLYING DISC STORE',
        'url'          => $block->getUrl(''),
    ],
    [
        'image_url'    => $block->getViewFileUrl('images/slider-1.webp'),
        'image_width'  => 1600,
        'image_height' => 624,
        'text_small'   => '',
        'text_large'   => 'THE FLYING DISC STORE',
        'url'          => $block->getUrl(''),
    ],
    [
        'image_url'    => $block->getViewFileUrl('images/slider-1.webp'),
        'image_width'  => 1600,
        'image_height' => 624,
        'text_small'   => '',
        'text_large'   => 'THE FLYING DISC STORE',
        'url'          => $block->getUrl(''),
    ],
];

?>
<div>
    <?=
    $sliderViewModel
        ->getSliderForItems(
            'Magento_Theme::elements/ui-slider/slider-item.phtml',
            $items,
            'Magento_Theme::elements/ui-slider/slider-php.phtml'
        )
        ->toHtml()
    ?>
</div>
